config/routes.rb
class AdminDomainConstraint
  def self.matches?(request)
    request.host == "threeohone.rwdev.io"
  end
end

Rails.application.routes.draw do
  constraints(AdminDomainConstraint) do
    resources :rules do
      collection do
        get "test"
      end
    end

    get "query", to: "redirects#query"
    root "rules#index"
  end

  match "*path", to: "redirects#go", via: :all, as: :go
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/result.rb
class Result
  attr_reader :url, :rule

  def self.redirect_url(url)
    last_updated_rule_timestamp = Rule.order(updated_at: :desc).first.updated_at.to_i
    cache_key = "#{last_updated_rule_timestamp}-#{url}"

    REDIRECT_CACHE.get(cache_key) || begin
      Rule.order(priority: :desc).find_each do |rule|
        result = Result.new(url, rule)
        if result.matches?
          REDIRECT_CACHE.set(cache_key, result.redirect_url)
          return result.redirect_url
        end
      end
    end
  end

  def self.find(url)
    results = []

    Rule.order(priority: :desc).find_each do |rule|
      result = Result.new(url, rule)
      results << result if result.matches?
    end

    results.reverse
  end

  def matches?
    match.present?
  end

  def match
    url.match(rule.requested_url)
  end

  def initialize(url, rule)
    @url = url
    @rule = rule
  end

  def redirect_url
    final_url = rule.destination_url

    while(placeholder_match = final_url.match(/\$(\d+)/))
      number = placeholder_match[1].to_i
      value = match[number].to_s
      final_url = final_url.gsub("$#{number}", value)
    end

    final_url
  end
end

app/models/rule.rb
class Rule < ApplicationRecord
  validates :priority, numericality: { only_integer: true }
  validates :requested_url, presence: true, uniqueness: true
  validates :destination_url, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/redirects_controller.rb
class RedirectsController < ApplicationController
  def go
    redirect_url = Result.redirect_url(request.url)

    if redirect_url
      redirect_to(redirect_url, status: :moved_permanently)
    else
      head 404
    end
  end

  def query
    redirect_url = Result.redirect_url(params[:url])

    if redirect_url
      json_result = { redirect_url: redirect_url }
    else
      json_result = { error: "No redirect found" }
    end

    render json: json_result
  end
end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
  def index
    @rules = Rule.order(priority: :desc)
  end

  def new
    @rule = Rule.new
  end

  def edit
    @rule = Rule.find(params[:id])
  end

  def create
    @rule = Rule.new(rule_params)

    if @rule.save
      flash[:success] = "Rule created successfully!"
      redirect_to(rules_path)
    else
      render(:new)
    end
  end

  def update
    @rule = Rule.find(params[:id])

    if @rule.update_attributes(rule_params)
      flash[:success] = "Rule updated successfully!"
      redirect_to(rules_path)
    else
      render(:edit)
    end
  end

  def destroy
    @rule = Rule.find(params[:id])

    if @rule.destroy
      flash[:success] = "Rule deleted successfully!"
      redirect_to(rules_path)
    else
      render(:edit)
    end
  end

  def test
    @results = Result.find(params[:url])
  end

  private

  def rule_params
    params.require(:rule).permit(
      :priority,
      :requested_url,
      :destination_url
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Three Oh One</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
      <a class="navbar-brand" href="#">Three Oh One</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Rules", rules_path, class: "nav-link" %>
          </li>
        </ul>

        <%= form_tag test_rules_path, method: :get, class: "form-inline my-2 my-lg-0" do |f| %>
          <input class="form-control mr-sm-2" name="url" type="text" placeholder="Enter a url to test" aria-label="Url">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Test</button>
        <% end %>
      </div>
    </nav>

    <div class="container">
      <div class="row">
        <div class="col-12">
          <% flash.each do |name, msg| -%>
            <div class="alert alert-<%= name %>" role="alert">
              <%= msg %>
            </div>
          <% end -%>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/rules/edit.html.erb
<div class="row">
  <div class="col-2">
      <%= link_to "Back", rules_path, class: "btn btn-info btn-block" %>
  </div>

  <div class="col-8">
    <h3>Edit Rule</h3>
    <%= bootstrap_form_for @rule do |f| %>
      <%= f.text_field :priority, type: "number", placeholder: "10", "data-toggle": "tooltip", "data-placement":"left", title:"Order in which to evaluate rules." %>
      <%= f.text_field :requested_url, placeholder: "http://written.rwdev.io/169188/swift-algorithm-club-august-2017-digest", "data-toggle": "tooltip", "data-placement":"left", title:"The requested url to match. Regex allowed." %>
      <%= f.text_field :destination_url, placeholder: "http://ios.rwdev.io/articles/169188", "data-toggle": "tooltip", "data-placement":"left", title:"The destination url to redirect the request to. Regex placeholder variables allowed." %>
      <%= f.submit "Save Rule", class: "btn btn-primary" %>
    <% end %>
  </div>

  <div class="col-2">
    <a href="#" class="btn btn-danger" role="button" data-toggle="modal" data-target="#deleteRule">Delete Rule</a>
  </div>
</div>

<div class="modal fade" id="deleteRule" tabindex="-1" role="dialog" aria-labelledby="deleteRuleLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteRuleTitle">Delete Rule?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you sure you wish to delete this rule?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <%= bootstrap_form_for @rule do |f| %>
          <%= button_to "Yes delete it", { action: "destroy", id: @rule.id }, class: "btn btn-danger", method: :delete %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/rules/index.html.erb
<div class="row">
  <div class="col-2">
    <%= link_to "Add New Rule", new_rule_path, class: "btn btn-success btn-block" %>
  </div>
  <div class="col-10">
    <h3>Rules by priority</h3>

    <table class="table table-hover">
      <thead>
        <tr>
          <th>Priority</th>
          <th>Requested URL</th>
          <th></th>
          <th>Destination URL</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @rules.each do |rule| %>
          <tr>
            <th><%= rule.priority %></th>
            <td><%= rule.requested_url %></td>
            <td><%= octicon "triangle-right" %></td>
            <td><%= rule.destination_url %></td>
            <td>
              <%= link_to octicon("pencil"), edit_rule_path(rule) %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/rules/new.html.erb
<div class="row">
  <div class="col-2">
      <%= link_to "Back", rules_path, class: "btn btn-info btn-block" %>
  </div>

  <div class="col-8">
    <h3>New Rule</h3>
    <%= bootstrap_form_for @rule do |f| %>
      <%= f.text_field :priority, type: "number", placeholder: "10", "data-toggle": "tooltip", "data-placement":"left", title:"Order in which to evaluate rules." %>
      <%= f.text_field :requested_url, placeholder: "http://written.rwdev.io/169188/swift-algorithm-club-august-2017-digest", "data-toggle": "tooltip", "data-placement":"left", title:"The requested url to match. Regex allowed." %>
      <%= f.text_field :destination_url, placeholder: "http://ios.rwdev.io/articles/169188", "data-toggle": "tooltip", "data-placement":"left", title:"The destination url to redirect the request to. Regex placeholder variables allowed." %>
      <%= f.submit "Create Rule", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/rules/test.html.erb
<div class="row">
  <div class="col-2">
    <%= link_to "Back", rules_path, class: "btn btn-info btn-block" %>
  </div>
  <div class="col-10">
    <h3><%= params[:url] %> Test Results</h3>

    <table class="table table-hover">
      <thead>
        <tr>
          <th>Order</th>
          <th>Matched Rule</th>
          <th></th>
          <th>Redirect URL</th>
        </tr>
      </thead>
      <tbody>
        <% @results.each_with_index do |result, index| %>
          <tr>
            <th><%= index + 1 %></th>
            <td><%= result.rule.requested_url %></td>
            <td><%= octicon "triangle-right" %></td>
            <td><%= result.redirect_url %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>